peer:
  id: peer1-buyer1
  networkId: dev
  address: 0.0.0.0:7051
  localMspId: Buyer1MSP
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore: /etc/hyperledger/msp/keystore
chaincode:
  externalBuilders:
    - name: myexternal
      path: /opt/hyperledger/external-builder # 这是 *容器内部* 的路径，在 docker-compose 中挂载脚本到此路径

        
